namespace ModelBuilder.Generator
{
    using System.Text;

    /// <summary>
    ///     The <see cref="SourceEmitter" /> class
    ///     renders the discovered build models into a single generated C# source file containing the
    ///     builders, the enum value sources, and their module-initializer registration.
    /// </summary>
    internal static class SourceEmitter
    {
        private const string Indent = "    ";

        public static string Emit(GenerationModel model)
        {
            return Emit(model, hasModuleInitializer: true);
        }

        public static string Emit(GenerationModel model, bool hasModuleInitializer)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            if (hasModuleInitializer == false)
            {
                EmitModuleInitializerPolyfill(builder);
            }

            builder.AppendLine("namespace ModelBuilder.Generated");
            builder.AppendLine("{");

            foreach (var buildable in model.Builders)
            {
                EmitBuilder(builder, buildable);
                builder.AppendLine();
            }

            foreach (var enumModel in model.Enums)
            {
                EmitEnumSource(builder, enumModel);
                builder.AppendLine();
            }

            foreach (var collection in model.Collections)
            {
                EmitCollectionSource(builder, collection);
                builder.AppendLine();
            }

            EmitRegistration(builder, model);

            builder.AppendLine("}");

            return builder.ToString();
        }

        private static void EmitEnumSource(StringBuilder builder, EnumModel model)
        {
            var type = model.FullyQualifiedName;

            builder.Append(Indent).AppendLine($"internal sealed class {model.SourceName}");
            builder.Append(Indent).AppendLine($"    : global::ModelBuilder.vNext.IValueSource<{type}>");
            builder.Append(Indent).AppendLine("{");

            if (model.MemberNames.Count == 0)
            {
                builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.vNext.BuildContext context, in global::ModelBuilder.vNext.BuildTarget target)");
                builder.Append(Indent).AppendLine("    {");
                builder.Append(Indent).AppendLine($"        return default({type});");
                builder.Append(Indent).AppendLine("    }");
                builder.Append(Indent).AppendLine("}");

                return;
            }

            if (model.IsFlags)
            {
                builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.vNext.BuildContext context, in global::ModelBuilder.vNext.BuildTarget target)");
                builder.Append(Indent).AppendLine("    {");
                builder.Append(Indent).AppendLine($"        var result = default({type});");

                foreach (var member in model.MemberNames)
                {
                    builder.Append(Indent).AppendLine($"        if (context.Random.NextBool()) result |= {type}.{member};");
                }

                builder.Append(Indent).AppendLine("        return result;");
                builder.Append(Indent).AppendLine("    }");
                builder.Append(Indent).AppendLine("}");

                return;
            }

            builder.Append(Indent).Append("    private static readonly ").Append(type).Append("[] _values = { ");

            var first = true;

            foreach (var member in model.MemberNames)
            {
                if (first == false)
                {
                    builder.Append(", ");
                }

                builder.Append(type).Append('.').Append(member);
                first = false;
            }

            builder.AppendLine(" };");
            builder.AppendLine();
            builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.vNext.BuildContext context, in global::ModelBuilder.vNext.BuildTarget target)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine("        return _values[context.Random.NextInt32(0, _values.Length - 1)];");
            builder.Append(Indent).AppendLine("    }");
            builder.Append(Indent).AppendLine("}");
        }

        private static void EmitModuleInitializerPolyfill(StringBuilder builder)
        {
            // Frameworks before net5.0 (e.g. net472 / netstandard2.0 consumers) lack
            // ModuleInitializerAttribute. The compiler honours any internal attribute of this exact
            // name and namespace, so a polyfill makes the generated [ModuleInitializer] compile there.
            builder.AppendLine("namespace System.Runtime.CompilerServices");
            builder.AppendLine("{");
            builder.Append(Indent).AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
            builder.Append(Indent).AppendLine("internal sealed class ModuleInitializerAttribute : global::System.Attribute");
            builder.Append(Indent).AppendLine("{");
            builder.Append(Indent).AppendLine("}");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        private static void EmitCollectionSource(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;

            builder.Append(Indent).AppendLine($"internal sealed class {model.SourceName}");
            builder.Append(Indent).AppendLine($"    : global::ModelBuilder.vNext.IValueSource<{slot}>");
            builder.Append(Indent).AppendLine("{");
            builder.Append(Indent).AppendLine($"    public {slot} Create(global::ModelBuilder.vNext.BuildContext context, in global::ModelBuilder.vNext.BuildTarget target)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine("        var count = context.NextCount();");

            switch (model.Kind)
            {
                case CollectionKind.Array:
                    builder.Append(Indent).AppendLine($"        var result = new {element}[count];");
                    builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
                    builder.Append(Indent).AppendLine("        {");
                    builder.Append(Indent).AppendLine($"            result[i] = context.Build<{element}>(typeof({slot}), \"item\");");
                    builder.Append(Indent).AppendLine("        }");

                    break;
                case CollectionKind.Set:
                    builder.Append(Indent).AppendLine($"        var result = new global::System.Collections.Generic.HashSet<{element}>();");
                    builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
                    builder.Append(Indent).AppendLine("        {");
                    builder.Append(Indent).AppendLine($"            result.Add(context.Build<{element}>(typeof({slot}), \"item\"));");
                    builder.Append(Indent).AppendLine("        }");

                    break;
                case CollectionKind.Dictionary:
                    builder.Append(Indent).AppendLine($"        var result = new global::System.Collections.Generic.Dictionary<{element}, {model.ValueType}>();");
                    builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
                    builder.Append(Indent).AppendLine("        {");
                    builder.Append(Indent).AppendLine($"            var key = context.Build<{element}>(typeof({slot}), \"key\");");

                    if (model.KeyCanBeNull)
                    {
                        builder.Append(Indent).AppendLine("            if (key is null) { continue; }");
                    }

                    builder.Append(Indent).AppendLine($"            result[key] = context.Build<{model.ValueType}>(typeof({slot}), \"value\");");
                    builder.Append(Indent).AppendLine("        }");

                    break;
                default:
                    builder.Append(Indent).AppendLine($"        var result = new global::System.Collections.Generic.List<{element}>(count);");
                    builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
                    builder.Append(Indent).AppendLine("        {");
                    builder.Append(Indent).AppendLine($"            result.Add(context.Build<{element}>(typeof({slot}), \"item\"));");
                    builder.Append(Indent).AppendLine("        }");

                    break;
            }

            builder.Append(Indent).AppendLine("        return result;");
            builder.Append(Indent).AppendLine("    }");
            builder.Append(Indent).AppendLine("}");
        }

        private static void EmitBuilder(StringBuilder builder, BuildableModel model)
        {
            var type = model.FullyQualifiedName;

            builder.Append(Indent).AppendLine($"internal sealed class {model.BuilderName}");
            builder.Append(Indent).AppendLine($"    : global::ModelBuilder.vNext.IModelBuilder<{type}>, global::ModelBuilder.vNext.IModelBuilder");
            builder.Append(Indent).AppendLine("{");

            // Generic Create
            builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.vNext.BuildContext context, params object?[]? args)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        using (context.Log.BeginScope(global::ModelBuilder.vNext.BuildLogEntryKind.CreateInstance, typeof({type})))");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).Append("            var instance = new ").Append(type).Append('(');
            EmitConstructorArguments(builder, model);
            builder.AppendLine(");");
            builder.Append(Indent).AppendLine("            return Populate(context, instance, args);");
            builder.Append(Indent).AppendLine("        }");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();

            // Generic Populate
            builder.Append(Indent).AppendLine($"    public {type} Populate(global::ModelBuilder.vNext.BuildContext context, {type} instance, object?[]? args = null)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        using (context.Log.BeginScope(global::ModelBuilder.vNext.BuildLogEntryKind.PopulateInstance, typeof({type})))");
            builder.Append(Indent).AppendLine($"        using (context.EnterSiblingScope())");
            builder.Append(Indent).AppendLine("        {");

            foreach (var member in model.Members)
            {
                builder.Append(Indent).AppendLine($"            if (context.ShouldPopulate(typeof({type}), \"{member.Name}\", typeof({member.TypeName})))");
                builder.Append(Indent).AppendLine("            {");
                builder.Append(Indent).AppendLine($"                instance.{member.Name} = context.Build<{member.TypeName}>(typeof({type}), \"{member.Name}\");");
                builder.Append(Indent).AppendLine($"                context.RecordSibling(\"{member.Name}\", instance.{member.Name});");
                builder.Append(Indent).AppendLine("            }");
            }

            builder.Append(Indent).AppendLine("        }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine("        return instance;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();

            // Non-generic surface
            builder.Append(Indent).AppendLine("    object global::ModelBuilder.vNext.IModelBuilder.Create(global::ModelBuilder.vNext.BuildContext context, params object?[]? args)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine("        return Create(context, args)!;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine("    object global::ModelBuilder.vNext.IModelBuilder.Populate(global::ModelBuilder.vNext.BuildContext context, object instance, object?[]? args)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        return Populate(context, ({type})instance, args)!;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine($"    global::System.Type global::ModelBuilder.vNext.IModelBuilder.BuildType => typeof({type});");
            builder.Append(Indent).AppendLine("}");
        }

        private static void EmitConstructorArguments(StringBuilder builder, BuildableModel model)
        {
            var first = true;

            foreach (var parameter in model.ConstructorParameters)
            {
                if (first == false)
                {
                    builder.Append(", ");
                }

                builder.Append($"context.Build<{parameter.TypeName}>(typeof({model.FullyQualifiedName}), \"{parameter.Name}\")");
                first = false;
            }
        }

        private static void EmitRegistration(StringBuilder builder, GenerationModel model)
        {
            builder.Append(Indent).AppendLine("internal static class GeneratedModelBuilderRegistration");
            builder.Append(Indent).AppendLine("{");
            builder.Append(Indent).AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.Append(Indent).AppendLine("    internal static void Initialize()");
            builder.Append(Indent).AppendLine("    {");

            foreach (var enumModel in model.Enums)
            {
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.vNext.ValueSource<{enumModel.FullyQualifiedName}>.Instance = new {enumModel.SourceName}();");
            }

            foreach (var underlying in model.NullableUnderlyingTypes)
            {
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.vNext.ValueSource<{underlying}?>.Instance = new global::ModelBuilder.vNext.NullableValueSource<{underlying}>();");
            }

            foreach (var collection in model.Collections)
            {
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.vNext.ValueSource<{collection.SlotType}>.Instance = new {collection.SourceName}();");
            }

            foreach (var buildable in model.Builders)
            {
                builder.Append(Indent).AppendLine($"        var {buildable.BuilderName}_instance = new {buildable.BuilderName}();");
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.vNext.ModelBuilderSlot<{buildable.FullyQualifiedName}>.Instance = {buildable.BuilderName}_instance;");
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.vNext.Model.Registry.Register({buildable.BuilderName}_instance);");
            }

            builder.Append(Indent).AppendLine("    }");
            builder.Append(Indent).AppendLine("}");
        }
    }
}
