namespace ModelBuilder.Generator
{
    using System.Collections.Immutable;
    using System.Text;

    /// <summary>
    ///     The <see cref="SourceEmitter" /> class
    ///     renders the discovered build models into a single generated C# source file containing the
    ///     builders and their module-initializer registration.
    /// </summary>
    internal static class SourceEmitter
    {
        private const string Indent = "    ";

        public static string Emit(ImmutableArray<BuildableModel> models)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("namespace ModelBuilder.Generated");
            builder.AppendLine("{");

            foreach (var model in models)
            {
                EmitBuilder(builder, model);
                builder.AppendLine();
            }

            EmitRegistration(builder, models);

            builder.AppendLine("}");

            return builder.ToString();
        }

        private static void EmitBuilder(StringBuilder builder, BuildableModel model)
        {
            var type = model.FullyQualifiedName;

            builder.Append(Indent).AppendLine($"internal sealed class {model.BuilderName}");
            builder.Append(Indent).AppendLine($"    : global::ModelBuilder.vNext.IModelBuilder<{type}>, global::ModelBuilder.vNext.IModelBuilder");
            builder.Append(Indent).AppendLine("{");

            // Generic Create
            builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.vNext.BuildContext context, params object?[]? args)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        using (context.Log.BeginScope(global::ModelBuilder.vNext.BuildLogEntryKind.CreateInstance, typeof({type})))");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).Append("            var instance = new ").Append(type).Append('(');
            EmitConstructorArguments(builder, model);
            builder.AppendLine(");");
            builder.Append(Indent).AppendLine("            return Populate(context, instance, args);");
            builder.Append(Indent).AppendLine("        }");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();

            // Generic Populate
            builder.Append(Indent).AppendLine($"    public {type} Populate(global::ModelBuilder.vNext.BuildContext context, {type} instance, object?[]? args = null)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        using (context.Log.BeginScope(global::ModelBuilder.vNext.BuildLogEntryKind.PopulateInstance, typeof({type})))");
            builder.Append(Indent).AppendLine("        {");

            foreach (var member in model.Members)
            {
                builder.Append(Indent).AppendLine($"            if (context.ShouldPopulate(typeof({type}), \"{member.Name}\", typeof({member.TypeName})))");
                builder.Append(Indent).AppendLine("            {");
                builder.Append(Indent).AppendLine($"                instance.{member.Name} = context.Build<{member.TypeName}>(typeof({type}), \"{member.Name}\");");
                builder.Append(Indent).AppendLine("            }");
            }

            builder.Append(Indent).AppendLine("        }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine("        return instance;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();

            // Non-generic surface
            builder.Append(Indent).AppendLine("    object global::ModelBuilder.vNext.IModelBuilder.Create(global::ModelBuilder.vNext.BuildContext context, params object?[]? args)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine("        return Create(context, args)!;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine("    object global::ModelBuilder.vNext.IModelBuilder.Populate(global::ModelBuilder.vNext.BuildContext context, object instance, object?[]? args)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        return Populate(context, ({type})instance, args)!;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine($"    global::System.Type global::ModelBuilder.vNext.IModelBuilder.BuildType => typeof({type});");
            builder.Append(Indent).AppendLine("}");
        }

        private static void EmitConstructorArguments(StringBuilder builder, BuildableModel model)
        {
            var first = true;

            foreach (var parameter in model.ConstructorParameters)
            {
                if (first == false)
                {
                    builder.Append(", ");
                }

                builder.Append($"context.Build<{parameter.TypeName}>(typeof({model.FullyQualifiedName}), \"{parameter.Name}\")");
                first = false;
            }
        }

        private static void EmitRegistration(StringBuilder builder, ImmutableArray<BuildableModel> models)
        {
            builder.Append(Indent).AppendLine("internal static class GeneratedModelBuilderRegistration");
            builder.Append(Indent).AppendLine("{");
            builder.Append(Indent).AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.Append(Indent).AppendLine("    internal static void Initialize()");
            builder.Append(Indent).AppendLine("    {");

            foreach (var model in models)
            {
                builder.Append(Indent).AppendLine($"        var {model.BuilderName}_instance = new {model.BuilderName}();");
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.vNext.ModelBuilderSlot<{model.FullyQualifiedName}>.Instance = {model.BuilderName}_instance;");
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.vNext.Model.Registry.Register({model.BuilderName}_instance);");
            }

            builder.Append(Indent).AppendLine("    }");
            builder.Append(Indent).AppendLine("}");
        }
    }
}
