namespace ModelBuilder.Generator
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    ///     The <see cref="SourceEmitter" /> class
    ///     renders the discovered build models into a single generated C# source file containing the
    ///     builders, the enum value sources, and their module-initializer registration.
    /// </summary>
    internal static class SourceEmitter
    {
        private const string Indent = "    ";

        public static string Emit(GenerationModel model)
        {
            return Emit(model, Array.Empty<string>(), hasModuleInitializer: true);
        }

        public static string Emit(
            GenerationModel model,
            IReadOnlyList<string> constructionTypeNames,
            bool hasModuleInitializer)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            if (hasModuleInitializer == false)
            {
                EmitModuleInitializerPolyfill(builder);
            }

            builder.AppendLine("namespace ModelBuilder.Generated");
            builder.AppendLine("{");

            foreach (var buildable in model.Builders)
            {
                EmitBuilder(builder, buildable);
                builder.AppendLine();
            }

            foreach (var enumModel in model.Enums)
            {
                EmitEnumSource(builder, enumModel);
                builder.AppendLine();
            }

            foreach (var collection in model.Collections)
            {
                EmitCollectionSource(builder, collection);
                builder.AppendLine();
            }

            EmitRegistration(builder, model);

            builder.AppendLine("}");

            EmitConstructionExtensions(builder, model, constructionTypeNames);

            return builder.ToString();
        }

        private static void EmitEnumSource(StringBuilder builder, EnumModel model)
        {
            var type = model.FullyQualifiedName;

            builder.Append(Indent).AppendLine($"internal sealed class {model.SourceName}");
            builder.Append(Indent).AppendLine($"    : global::ModelBuilder.IValueSource<{type}>");
            builder.Append(Indent).AppendLine("{");

            if (model.MemberNames.Count == 0)
            {
                builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.IBuildContext context, in global::ModelBuilder.BuildTarget target)");
                builder.Append(Indent).AppendLine("    {");
                builder.Append(Indent).AppendLine($"        return default({type});");
                builder.Append(Indent).AppendLine("    }");
                builder.Append(Indent).AppendLine("}");

                return;
            }

            if (model.IsFlags)
            {
                builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.IBuildContext context, in global::ModelBuilder.BuildTarget target)");
                builder.Append(Indent).AppendLine("    {");
                builder.Append(Indent).AppendLine($"        var result = default({type});");

                foreach (var member in model.MemberNames)
                {
                    builder.Append(Indent).AppendLine($"        if (context.Random.NextBool()) result |= {type}.{member};");
                }

                builder.Append(Indent).AppendLine("        return result;");
                builder.Append(Indent).AppendLine("    }");
                builder.Append(Indent).AppendLine("}");

                return;
            }

            builder.Append(Indent).Append("    private static readonly ").Append(type).Append("[] _values = { ");

            var first = true;

            foreach (var member in model.MemberNames)
            {
                if (first == false)
                {
                    builder.Append(", ");
                }

                builder.Append(type).Append('.').Append(member);
                first = false;
            }

            builder.AppendLine(" };");
            builder.AppendLine();
            builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.IBuildContext context, in global::ModelBuilder.BuildTarget target)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine("        return _values[context.Random.NextInt32(0, _values.Length - 1)];");
            builder.Append(Indent).AppendLine("    }");
            builder.Append(Indent).AppendLine("}");
        }

        private static void EmitModuleInitializerPolyfill(StringBuilder builder)
        {
            // Frameworks before net5.0 (e.g. net472 / netstandard2.0 consumers) lack
            // ModuleInitializerAttribute. The compiler honours any internal attribute of this exact
            // name and namespace, so a polyfill makes the generated [ModuleInitializer] compile there.
            builder.AppendLine("namespace System.Runtime.CompilerServices");
            builder.AppendLine("{");
            builder.Append(Indent).AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
            builder.Append(Indent).AppendLine("internal sealed class ModuleInitializerAttribute : global::System.Attribute");
            builder.Append(Indent).AppendLine("{");
            builder.Append(Indent).AppendLine("}");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        private static void EmitCollectionSource(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;

            builder.Append(Indent).AppendLine($"internal sealed class {model.SourceName}");
            builder.Append(Indent).AppendLine($"    : global::ModelBuilder.IValueSource<{slot}>");
            builder.Append(Indent).AppendLine("{");
            builder.Append(Indent).AppendLine($"    public {slot} Create(global::ModelBuilder.IBuildContext context, in global::ModelBuilder.BuildTarget target)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine("        var count = context.NextCount();");

            switch (model.Kind)
            {
                case CollectionKind.Array:
                    EmitArrayBody(builder, model);

                    break;
                case CollectionKind.List:
                case CollectionKind.Set:
                case CollectionKind.Collection:
                case CollectionKind.Queue:
                case CollectionKind.Stack:
                case CollectionKind.SortedSet:
                case CollectionKind.ObservableCollection:
                case CollectionKind.ConcurrentBag:
                case CollectionKind.ConcurrentQueue:
                case CollectionKind.ConcurrentStack:
                    EmitAddBasedBody(builder, model, model.Kind);

                    break;
                case CollectionKind.Dictionary:
                case CollectionKind.SortedDictionary:
                case CollectionKind.SortedList:
                case CollectionKind.ConcurrentDictionary:
                    EmitKeyedBody(builder, model);

                    break;
                case CollectionKind.ReadOnlyCollection:
                    EmitReadOnlyCollectionBody(builder, model);

                    break;
                case CollectionKind.ReadOnlyDictionary:
                    EmitReadOnlyDictionaryBody(builder, model);

                    break;
                case CollectionKind.ReadOnlyObservableCollection:
                    EmitReadOnlyObservableCollectionBody(builder, model);

                    break;
                case CollectionKind.ImmutableArray:
                case CollectionKind.ImmutableList:
                case CollectionKind.ImmutableHashSet:
                case CollectionKind.ImmutableSortedSet:
                case CollectionKind.ImmutableQueue:
                case CollectionKind.ImmutableStack:
                    EmitImmutableSingleBody(builder, model);

                    break;
                case CollectionKind.ImmutableDictionary:
                case CollectionKind.ImmutableSortedDictionary:
                    EmitImmutableDictionaryBody(builder, model);

                    break;
                default:
                    EmitAddBasedBody(builder, model, CollectionKind.List);

                    break;
            }

            builder.Append(Indent).AppendLine("        return result;");
            builder.Append(Indent).AppendLine("    }");
            builder.Append(Indent).AppendLine("}");
        }

        private static void EmitArrayBody(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;

            builder.Append(Indent).AppendLine($"        var result = new {element}[count];");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).AppendLine($"            result[i] = context.Build<{element}>(typeof({slot}), \"item\", i);");
            builder.Append(Indent).AppendLine("        }");
        }

        private static string GetAddBasedBackingTypeName(CollectionKind kind, string element)
        {
            return kind switch
            {
                CollectionKind.List => $"global::System.Collections.Generic.List<{element}>",
                CollectionKind.Set => $"global::System.Collections.Generic.HashSet<{element}>",
                CollectionKind.Collection => $"global::System.Collections.ObjectModel.Collection<{element}>",
                CollectionKind.Queue => $"global::System.Collections.Generic.Queue<{element}>",
                CollectionKind.Stack => $"global::System.Collections.Generic.Stack<{element}>",
                CollectionKind.SortedSet => $"global::System.Collections.Generic.SortedSet<{element}>",
                CollectionKind.ObservableCollection => $"global::System.Collections.ObjectModel.ObservableCollection<{element}>",
                CollectionKind.ConcurrentBag => $"global::System.Collections.Concurrent.ConcurrentBag<{element}>",
                CollectionKind.ConcurrentQueue => $"global::System.Collections.Concurrent.ConcurrentQueue<{element}>",
                CollectionKind.ConcurrentStack => $"global::System.Collections.Concurrent.ConcurrentStack<{element}>",
                _ => $"global::System.Collections.Generic.List<{element}>"
            };
        }

        private static string GetAddMethodName(CollectionKind kind)
        {
            return kind switch
            {
                CollectionKind.Queue => "Enqueue",
                CollectionKind.ConcurrentQueue => "Enqueue",
                CollectionKind.Stack => "Push",
                CollectionKind.ConcurrentStack => "Push",
                _ => "Add"
            };
        }

        private static void EmitAddBasedBody(StringBuilder builder, CollectionModel model, CollectionKind kind)
        {
            var slot = model.SlotType;
            var element = model.ElementType;
            var backingType = model.IsCustomType ? slot : GetAddBasedBackingTypeName(kind, element);
            var addMethod = GetAddMethodName(kind);
            var constructorArgs = kind == CollectionKind.List && model.IsCustomType == false ? "count" : string.Empty;

            builder.Append(Indent).AppendLine($"        var result = new {backingType}({constructorArgs});");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).AppendLine($"            result.{addMethod}(context.Build<{element}>(typeof({slot}), \"item\", i));");
            builder.Append(Indent).AppendLine("        }");
        }

        private static string GetKeyedBackingTypeName(CollectionKind kind, string element, string value)
        {
            return kind switch
            {
                CollectionKind.SortedDictionary => $"global::System.Collections.Generic.SortedDictionary<{element}, {value}>",
                CollectionKind.SortedList => $"global::System.Collections.Generic.SortedList<{element}, {value}>",
                CollectionKind.ConcurrentDictionary => $"global::System.Collections.Concurrent.ConcurrentDictionary<{element}, {value}>",
                _ => $"global::System.Collections.Generic.Dictionary<{element}, {value}>"
            };
        }

        private static void EmitKeyedBody(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;
            var value = model.ValueType;
            var backingType = model.IsCustomType ? slot : GetKeyedBackingTypeName(model.Kind, element, value);

            builder.Append(Indent).AppendLine($"        var result = new {backingType}();");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");

            if (model.RetryOnKeyCollision)
            {
                builder.Append(Indent).AppendLine($"            {element} key;");
                builder.Append(Indent).AppendLine("            var attempts = 0;");
                builder.Append(Indent).AppendLine("            do");
                builder.Append(Indent).AppendLine("            {");
                builder.Append(Indent).AppendLine($"                key = context.Build<{element}>(typeof({slot}), \"key\", i);");
                builder.Append(Indent).AppendLine("                attempts++;");
                builder.Append(Indent).AppendLine("            }");

                if (model.KeyCanBeNull)
                {
                    builder.Append(Indent).AppendLine("            while ((key is null || result.ContainsKey(key)) && attempts < 10);");
                    builder.Append(Indent).AppendLine("            if (key is null) { continue; }");
                }
                else
                {
                    builder.Append(Indent).AppendLine("            while (result.ContainsKey(key) && attempts < 10);");
                }
            }
            else
            {
                builder.Append(Indent).AppendLine($"            var key = context.Build<{element}>(typeof({slot}), \"key\", i);");

                if (model.KeyCanBeNull)
                {
                    builder.Append(Indent).AppendLine("            if (key is null) { continue; }");
                }
            }

            builder.Append(Indent).AppendLine($"            result[key] = context.Build<{value}>(typeof({slot}), \"value\", i);");
            builder.Append(Indent).AppendLine("        }");
        }

        private static void EmitReadOnlyCollectionBody(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;

            builder.Append(Indent).AppendLine($"        var backing = new global::System.Collections.Generic.List<{element}>(count);");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).AppendLine($"            backing.Add(context.Build<{element}>(typeof({slot}), \"item\", i));");
            builder.Append(Indent).AppendLine("        }");
            builder.Append(Indent).AppendLine($"        var result = new global::System.Collections.ObjectModel.ReadOnlyCollection<{element}>(backing);");
        }

        private static void EmitReadOnlyDictionaryBody(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;
            var value = model.ValueType;

            builder.Append(Indent).AppendLine($"        var backing = new global::System.Collections.Generic.Dictionary<{element}, {value}>();");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).AppendLine($"            var key = context.Build<{element}>(typeof({slot}), \"key\", i);");

            if (model.KeyCanBeNull)
            {
                builder.Append(Indent).AppendLine("            if (key is null) { continue; }");
            }

            builder.Append(Indent).AppendLine($"            backing[key] = context.Build<{value}>(typeof({slot}), \"value\", i);");
            builder.Append(Indent).AppendLine("        }");
            builder.Append(Indent)
                .AppendLine($"        var result = new global::System.Collections.ObjectModel.ReadOnlyDictionary<{element}, {value}>(backing);");
        }

        private static void EmitReadOnlyObservableCollectionBody(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;

            builder.Append(Indent).AppendLine($"        var backing = new global::System.Collections.ObjectModel.ObservableCollection<{element}>();");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).AppendLine($"            backing.Add(context.Build<{element}>(typeof({slot}), \"item\", i));");
            builder.Append(Indent).AppendLine("        }");
            builder.Append(Indent)
                .AppendLine($"        var result = new global::System.Collections.ObjectModel.ReadOnlyObservableCollection<{element}>(backing);");
        }

        private static string GetImmutableFactoryTypeName(CollectionKind kind)
        {
            return kind switch
            {
                CollectionKind.ImmutableArray => "global::System.Collections.Immutable.ImmutableArray",
                CollectionKind.ImmutableList => "global::System.Collections.Immutable.ImmutableList",
                CollectionKind.ImmutableHashSet => "global::System.Collections.Immutable.ImmutableHashSet",
                CollectionKind.ImmutableSortedSet => "global::System.Collections.Immutable.ImmutableSortedSet",
                CollectionKind.ImmutableQueue => "global::System.Collections.Immutable.ImmutableQueue",
                CollectionKind.ImmutableStack => "global::System.Collections.Immutable.ImmutableStack",
                CollectionKind.ImmutableDictionary => "global::System.Collections.Immutable.ImmutableDictionary",
                CollectionKind.ImmutableSortedDictionary => "global::System.Collections.Immutable.ImmutableSortedDictionary",
                _ => "global::System.Collections.Immutable.ImmutableList"
            };
        }

        private static void EmitImmutableSingleBody(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;
            var factory = GetImmutableFactoryTypeName(model.Kind);

            builder.Append(Indent).AppendLine($"        var backing = new global::System.Collections.Generic.List<{element}>(count);");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).AppendLine($"            backing.Add(context.Build<{element}>(typeof({slot}), \"item\", i));");
            builder.Append(Indent).AppendLine("        }");
            builder.Append(Indent).AppendLine($"        var result = {factory}.CreateRange(backing);");
        }

        private static void EmitImmutableDictionaryBody(StringBuilder builder, CollectionModel model)
        {
            var slot = model.SlotType;
            var element = model.ElementType;
            var value = model.ValueType;
            var factory = GetImmutableFactoryTypeName(model.Kind);

            builder.Append(Indent).AppendLine($"        var backing = new global::System.Collections.Generic.Dictionary<{element}, {value}>();");
            builder.Append(Indent).AppendLine("        for (var i = 0; i < count; i++)");
            builder.Append(Indent).AppendLine("        {");
            builder.Append(Indent).AppendLine($"            var key = context.Build<{element}>(typeof({slot}), \"key\", i);");

            if (model.KeyCanBeNull)
            {
                builder.Append(Indent).AppendLine("            if (key is null) { continue; }");
            }

            builder.Append(Indent).AppendLine($"            backing[key] = context.Build<{value}>(typeof({slot}), \"value\", i);");
            builder.Append(Indent).AppendLine("        }");
            builder.Append(Indent).AppendLine($"        var result = {factory}.CreateRange(backing);");
        }


        private static void EmitBuilder(StringBuilder builder, BuildableModel model)
        {
            var type = model.FullyQualifiedName;

            builder.Append(Indent).AppendLine($"internal sealed class {model.BuilderName}");
            builder.Append(Indent).AppendLine($"    : global::ModelBuilder.IModelBuilder<{type}>, global::ModelBuilder.IModelBuilder");
            builder.Append(Indent).AppendLine("{");

            // Generic Create
            builder.Append(Indent).AppendLine($"    public {type} Create(global::ModelBuilder.IBuildContext context)");
            builder.Append(Indent).AppendLine("    {");

            var selectedParameters = model.ConstructorParameters;

            if (selectedParameters.Count == 0)
            {
                builder.Append(Indent).AppendLine($"        using (context.Log.BeginScope(global::ModelBuilder.BuildLogEntryKind.CreateInstance, typeof({type})))");
                builder.Append(Indent).AppendLine("        {");
                builder.Append(Indent).Append("            var instance = new ").Append(type).AppendLine("();");
                builder.Append(Indent).AppendLine("            return Populate(context, instance);");
                builder.Append(Indent).AppendLine("        }");
            }
            else
            {
                builder.Append(Indent).AppendLine($"        using (context.Log.BeginScope(global::ModelBuilder.BuildLogEntryKind.CreateInstance, typeof({type})))");
                builder.Append(Indent).AppendLine("        using (context.EnterSiblingScope())");
                builder.Append(Indent).AppendLine("        {");

                // Build each constructor argument into a local and record it as a sibling under the
                // parameter name, in declaration order, so later arguments and the populated members can
                // derive from earlier ones (for example an Email member from firstName/lastName
                // parameters that are never exposed as properties).
                for (var index = 0; index < selectedParameters.Count; index++)
                {
                    var parameter = selectedParameters[index];

                    if (parameter.DefaultLiteral != null)
                    {
                        // An optional parameter: use its declared default when configured, otherwise build a value.
                        builder.Append(Indent).AppendLine($"            var __arg{index} = context.UseConstructorDefaults ? {parameter.DefaultLiteral} : context.Build<{parameter.TypeName}>(typeof({type}), \"{parameter.Name}\");");
                    }
                    else
                    {
                        builder.Append(Indent).AppendLine($"            var __arg{index} = context.Build<{parameter.TypeName}>(typeof({type}), \"{parameter.Name}\");");
                    }

                    builder.Append(Indent).AppendLine($"            context.RecordSibling(\"{parameter.Name}\", __arg{index});");
                }

                builder.Append(Indent).Append("            var instance = new ").Append(type).Append('(');

                for (var index = 0; index < selectedParameters.Count; index++)
                {
                    if (index > 0)
                    {
                        builder.Append(", ");
                    }

                    builder.Append("__arg").Append(index);
                }

                builder.AppendLine(");");

                EmitComplementMembers(builder, Indent + "            ", type, model.Members, selectedParameters);

                builder.Append(Indent).AppendLine("            return instance;");
                builder.Append(Indent).AppendLine("        }");
            }

            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();

            // Generic Populate
            builder.Append(Indent).AppendLine($"    public {type} Populate(global::ModelBuilder.IBuildContext context, {type} instance)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        using (context.Log.BeginScope(global::ModelBuilder.BuildLogEntryKind.PopulateInstance, typeof({type})))");
            builder.Append(Indent).AppendLine($"        using (context.EnterSiblingScope())");
            builder.Append(Indent).AppendLine("        {");

            foreach (var member in model.Members)
            {
                builder.Append(Indent).AppendLine($"            if (context.ShouldPopulate(typeof({type}), \"{member.Name}\", typeof({member.TypeName})))");
                builder.Append(Indent).AppendLine("            {");
                builder.Append(Indent).AppendLine($"                if (context.RetainAssignedValues == false || global::System.Collections.Generic.EqualityComparer<{member.TypeName}>.Default.Equals(instance.{member.Name}!, default({member.TypeName})!))");
                builder.Append(Indent).AppendLine("                {");
                builder.Append(Indent).AppendLine($"                    instance.{member.Name} = context.Build<{member.TypeName}>(typeof({type}), \"{member.Name}\");");
                builder.Append(Indent).AppendLine("                }");
                builder.Append(Indent).AppendLine($"                context.RecordSibling(\"{member.Name}\", instance.{member.Name});");
                builder.Append(Indent).AppendLine("            }");
            }

            builder.Append(Indent).AppendLine("        }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine("        return instance;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();

            // Non-generic surface
            builder.Append(Indent).AppendLine("    object global::ModelBuilder.IModelBuilder.Create(global::ModelBuilder.IBuildContext context)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine("        return Create(context)!;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine("    object global::ModelBuilder.IModelBuilder.Populate(global::ModelBuilder.IBuildContext context, object instance)");
            builder.Append(Indent).AppendLine("    {");
            builder.Append(Indent).AppendLine($"        return Populate(context, ({type})instance)!;");
            builder.Append(Indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(Indent).AppendLine($"    global::System.Type global::ModelBuilder.IModelBuilder.BuildType => typeof({type});");
            builder.Append(Indent).AppendLine("}");
        }

        private static void EmitComplementMembers(
            StringBuilder builder,
            string indent,
            string type,
            EquatableArray<MemberModel> members,
            EquatableArray<MemberModel> ctorParameters)
        {
            foreach (var member in members)
            {
                if (MatchingParameterIndex(member, ctorParameters) >= 0)
                {
                    continue;
                }

                builder.Append(indent).AppendLine($"if (context.ShouldPopulate(typeof({type}), \"{member.Name}\", typeof({member.TypeName})))");
                builder.Append(indent).AppendLine("{");
                builder.Append(indent).Append(Indent).AppendLine($"if (context.RetainAssignedValues == false || global::System.Collections.Generic.EqualityComparer<{member.TypeName}>.Default.Equals(instance.{member.Name}!, default({member.TypeName})!))");
                builder.Append(indent).Append(Indent).AppendLine("{");
                builder.Append(indent).Append(Indent).Append(Indent).AppendLine($"instance.{member.Name} = context.Build<{member.TypeName}>(typeof({type}), \"{member.Name}\");");
                builder.Append(indent).Append(Indent).AppendLine("}");
                builder.Append(indent).Append(Indent).AppendLine($"context.RecordSibling(\"{member.Name}\", instance.{member.Name});");
                builder.Append(indent).AppendLine("}");
            }
        }

        private static int MatchingParameterIndex(MemberModel member, EquatableArray<MemberModel> ctorParameters)
        {
            for (var index = 0; index < ctorParameters.Count; index++)
            {
                var parameter = ctorParameters[index];

                if (string.Equals(parameter.Name, member.Name, StringComparison.OrdinalIgnoreCase)
                    && string.Equals(parameter.TypeName, member.TypeName, StringComparison.Ordinal))
                {
                    return index;
                }
            }

            return -1;
        }

        private static void EmitConstructionExtensions(
            StringBuilder builder,
            GenerationModel model,
            IReadOnlyList<string> constructionRequests)
        {
            if (constructionRequests.Count == 0)
            {
                return;
            }

            var modelsByName = new Dictionary<string, BuildableModel>(StringComparer.Ordinal);

            foreach (var buildable in model.Builders)
            {
                modelsByName[buildable.FullyQualifiedName] = buildable;
            }

            // Collect the distinct requested types that have a builder. A single extension class is
            // emitted into the ModelBuilder namespace: any call site that writes Model.Construct<T>()
            // with Model unqualified necessarily has `using ModelBuilder;` (or a global using) in scope,
            // which also brings these From overloads into scope, so no per-namespace emission is needed.
            var types = new List<BuildableModel>();
            var seen = new HashSet<string>(StringComparer.Ordinal);

            foreach (var typeName in constructionRequests)
            {
                if (seen.Add(typeName) == false)
                {
                    continue;
                }

                if (modelsByName.TryGetValue(typeName, out var buildable))
                {
                    types.Add(buildable);
                }
            }

            if (types.Count == 0)
            {
                return;
            }

            EmitConstructionExtensionClass(builder, types);
        }

        private static void EmitConstructionExtensionClass(
            StringBuilder builder,
            List<BuildableModel> types)
        {
            builder.AppendLine();
            builder.AppendLine("namespace ModelBuilder");
            builder.AppendLine("{");

            builder.Append(Indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"ModelBuilder.Generator\", null)]");
            builder.Append(Indent).AppendLine("internal static class GeneratedConstructionExtensions");
            builder.Append(Indent).AppendLine("{");

            var first = true;

            foreach (var model in types)
            {
                foreach (var constructor in model.AllConstructors)
                {
                    if (first == false)
                    {
                        builder.AppendLine();
                    }

                    EmitFromOverload(builder, Indent + Indent, model, constructor);
                    first = false;
                }
            }

            builder.Append(Indent).AppendLine("}");
            builder.AppendLine("}");
        }

        private static void EmitFromOverload(
            StringBuilder builder,
            string indent,
            BuildableModel model,
            ConstructorModel constructor)
        {
            var type = model.FullyQualifiedName;
            var parameters = constructor.Parameters;

            foreach (var docLine in constructor.DocLines)
            {
                builder.Append(indent).AppendLine(docLine);
            }

            builder.Append(indent).Append($"public static {type} From(this global::ModelBuilder.Construction<{type}> construction");

            for (var index = 0; index < parameters.Count; index++)
            {
                var parameter = parameters[index];

                builder.Append($", {parameter.TypeName} {parameter.Name}");

                if (parameter.DefaultLiteral != null)
                {
                    builder.Append($" = {parameter.DefaultLiteral}");
                }
            }

            builder.AppendLine(")");
            builder.Append(indent).AppendLine("{");

            var body = indent + Indent;

            builder.Append(body).AppendLine("return construction.Execute(context =>");
            builder.Append(body).AppendLine("{");

            var lambda = body + Indent;

            builder.Append(lambda).AppendLine($"using (context.Log.BeginScope(global::ModelBuilder.BuildLogEntryKind.CreateInstance, typeof({type})))");
            builder.Append(lambda).AppendLine("using (context.EnterSiblingScope())");
            builder.Append(lambda).AppendLine("{");

            var inner = lambda + Indent;

            builder.Append(inner).Append($"var instance = new {type}(");

            for (var index = 0; index < parameters.Count; index++)
            {
                if (index > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(parameters[index].Name);
            }

            builder.AppendLine(");");

            // Record each constructor argument as a sibling under the parameter name so the populated
            // members can derive from them (e.g. an Email member from firstName/lastName), even when the
            // parameters are not exposed as properties.
            for (var index = 0; index < parameters.Count; index++)
            {
                builder.Append(inner).AppendLine($"context.RecordSibling(\"{parameters[index].Name}\", {parameters[index].Name});");
            }

            EmitComplementMembers(builder, inner, type, model.Members, parameters);

            builder.Append(inner).AppendLine("return instance;");
            builder.Append(lambda).AppendLine("}");
            builder.Append(body).AppendLine("});");
            builder.Append(indent).AppendLine("}");
        }

        private static void EmitRegistration(StringBuilder builder, GenerationModel model)
        {
            builder.Append(Indent).AppendLine("internal static class GeneratedModelBuilderRegistration");
            builder.Append(Indent).AppendLine("{");
            builder.Append(Indent).AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.Append(Indent).AppendLine("    internal static void Initialize()");
            builder.Append(Indent).AppendLine("    {");

            foreach (var enumModel in model.Enums)
            {
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.ValueSource<{enumModel.FullyQualifiedName}>.Instance = new {enumModel.SourceName}();");
                builder.Append(Indent)
                    .AppendLine($"        global::ModelBuilder.Model.RegisterValueSource<{enumModel.FullyQualifiedName}>(new {enumModel.SourceName}());");
            }

            foreach (var underlying in model.NullableUnderlyingTypes)
            {
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.ValueSource<{underlying}?>.Instance = new global::ModelBuilder.NullableValueSource<{underlying}>();");
                builder.Append(Indent)
                    .AppendLine(
                        $"        global::ModelBuilder.Model.RegisterValueSource<{underlying}?>(new global::ModelBuilder.NullableValueSource<{underlying}>());");
            }

            foreach (var collection in model.Collections)
            {
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.ValueSource<{collection.SlotType}>.Instance = new {collection.SourceName}();");
                builder.Append(Indent)
                    .AppendLine($"        global::ModelBuilder.Model.RegisterValueSource<{collection.SlotType}>(new {collection.SourceName}());");
            }

            foreach (var buildable in model.Builders)
            {
                builder.Append(Indent).AppendLine($"        var {buildable.BuilderName}_instance = new {buildable.BuilderName}();");
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.ModelBuilderSlot<{buildable.FullyQualifiedName}>.Instance = {buildable.BuilderName}_instance;");
                builder.Append(Indent).AppendLine($"        global::ModelBuilder.Model.Registry.Register({buildable.BuilderName}_instance);");
            }

            builder.Append(Indent).AppendLine("    }");
            builder.Append(Indent).AppendLine("}");
        }
    }
}
