//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null, white space or empty.
        /// </summary>
        internal static string ArgumentException_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentException_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public constructor is available for type {0}.
        /// </summary>
        internal static string ConstructorResolver_NoPublicConstructorFound {
            get {
                return ResourceManager.GetString("ConstructorResolver_NoPublicConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid constructors are available for type {0}.
        /// </summary>
        internal static string ConstructorResolver_NoValidConstructorFound {
            get {
                return ResourceManager.GetString("ConstructorResolver_NoValidConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected circular reference building type {0}, using previously created instance.
        /// </summary>
        internal static string DefaultBuildLog_CircularReferenceDetected {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created parameter {0} ({1}) for type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedParameter {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End creating type {0}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating parameter {0} ({1}) for type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingParameter {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start creating type {0} using {1}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0} value using {1}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingValue {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_IgnoringProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_IgnoringProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped type requested from {0} to {1}.
        /// </summary>
        internal static string DefaultBuildLog_MappingType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_MappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End populating instance {0}.
        /// </summary>
        internal static string DefaultBuildLog_PopulatedInstance {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PopulatedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start populating instance {0}.
        /// </summary>
        internal static string DefaultBuildLog_PopulatingInstance {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PopulatingInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running PostBuild on {0} using {1}.
        /// </summary>
        internal static string DefaultBuildLog_PostBuild {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PostBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructor found matching type..
        /// </summary>
        internal static string DefaultTypeCreator_NoMatchingConstructor {
            get {
                return ResourceManager.GetString("DefaultTypeCreator_NoMatchingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; does not refer to a property.
        /// </summary>
        internal static string Error_ExpressionNotPropertyFormat {
            get {
                return ResourceManager.GetString("Error_ExpressionNotPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression returned a property {0} that was not defined on type &apos;{1}&apos;.
        /// </summary>
        internal static string Error_ExpressionTargetsWrongType {
            get {
                return ResourceManager.GetString("Error_ExpressionTargetsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support the {1} type and reference name {2} in the context of the current build chain.
        /// </summary>
        internal static string Error_GenerationNotSupportedFormat {
            get {
                return ResourceManager.GetString("Error_GenerationNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support the {1} type.
        /// </summary>
        internal static string Error_TypeNotSupportedFormat {
            get {
                return ResourceManager.GetString("Error_TypeNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BuildChain property on the execution strategy is null.
        /// </summary>
        internal static string ExecuteStrategy_NoBuildChain {
            get {
                return ResourceManager.GetString("ExecuteStrategy_NoBuildChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class does not support creating values for parameters..
        /// </summary>
        internal static string ExpressionCreationRule_CreateWithParameterNotSupported {
            get {
                return ResourceManager.GetString("ExpressionCreationRule_CreateWithParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class does not support creating values for types..
        /// </summary>
        internal static string ExpressionCreationRule_CreateWithTypeNotSupported {
            get {
                return ResourceManager.GetString("ExpressionCreationRule_CreateWithTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not assignable to {1}.
        /// </summary>
        internal static string TypeMappingRule_TypeNotAssignable {
            get {
                return ResourceManager.GetString("TypeMappingRule_TypeNotAssignable", resourceCulture);
            }
        }
    }
}
