//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBuilder.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelBuilder.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null, white space or empty.
        /// </summary>
        internal static string ArgumentException_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentException_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not return an {1} instance. A build log is required to create an {2} instance.
        /// </summary>
        internal static string BuildStrategy_BuildLogRequired {
            get {
                return ResourceManager.GetString("BuildStrategy_BuildLogRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ConstructorResolver is null. A constructor resolver must be provided in order to create a build strategy.
        /// </summary>
        internal static string BuildStrategyCompiler_NullConstructorResolver {
            get {
                return ResourceManager.GetString("BuildStrategyCompiler_NullConstructorResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyResolver is null. A property resolver must be provided in order to create a build strategy.
        /// </summary>
        internal static string BuildStrategyCompiler_NullPropertyResolver {
            get {
                return ResourceManager.GetString("BuildStrategyCompiler_NullPropertyResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abata
        ///Abatz
        ///Abbott Group
        ///Abbott Inc
        ///Abbott LLC
        ///Abbott, Eichmann and Miller
        ///Abbott, Swift and Prosacco
        ///Abbott, Wehner and Nitzsche
        ///Abbott-Cole
        ///Abbott-Harvey
        ///Abbott-Kunde
        ///Abbott-McDermott
        ///Abbott-Walker
        ///Abernathy and Sons
        ///Abernathy Group
        ///Abernathy Inc
        ///Abernathy LLC
        ///Abernathy, Bartell and Block
        ///Abernathy, Jast and Anderson
        ///Abernathy, Klocko and Kutch
        ///Abernathy, Langosh and Corkery
        ///Abernathy, Marvin and Reilly
        ///Abernathy, Medhurst and MacGyver
        ///Abernathy, Streich and Pouros
        ///Abernathy, Zulau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public constructor is available for type {0}.
        /// </summary>
        internal static string ConstructorResolver_NoPublicConstructorFound {
            get {
                return ResourceManager.GetString("ConstructorResolver_NoPublicConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid constructors are available for type {0}.
        /// </summary>
        internal static string ConstructorResolver_NoValidConstructorFound {
            get {
                return ResourceManager.GetString("ConstructorResolver_NoValidConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aa-DJ
        ///aa-ER
        ///aa-ET
        ///af
        ///af-NA
        ///af-ZA
        ///agq
        ///agq-CM
        ///ak
        ///ak-GH
        ///am
        ///am-ET
        ///ar
        ///ar-001
        ///ar-AE
        ///ar-BH
        ///ar-DJ
        ///ar-DZ
        ///ar-EG
        ///ar-ER
        ///ar-IL
        ///ar-IQ
        ///ar-JO
        ///ar-KM
        ///ar-KW
        ///ar-LB
        ///ar-LY
        ///ar-MA
        ///ar-MR
        ///ar-OM
        ///ar-PS
        ///ar-QA
        ///ar-SA
        ///ar-SD
        ///ar-SO
        ///ar-SS
        ///ar-SY
        ///ar-TD
        ///ar-TN
        ///ar-YE
        ///arn
        ///arn-CL
        ///as
        ///as-IN
        ///asa
        ///asa-TZ
        ///ast
        ///ast-ES
        ///az
        ///az-Cyrl
        ///az-Cyrl-AZ
        ///az-Latn
        ///az-Latn-AZ
        ///ba
        ///ba-RU
        ///bas
        ///bas-CM
        ///be
        ///be-BY
        ///bem
        ///bem-ZM
        ///bez
        ///bez-TZ
        ///bg
        ///bg-BG
        ///bin
        ///bin-NG
        ///bm
        ///bm-Latn
        ///bm-Latn-ML
        ///bn
        ///bn-BD
        ///bn-IN
        ///bo
        ///bo-CN
        ///bo-IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected circular reference building type {0}, using previously created instance.
        /// </summary>
        internal static string DefaultBuildLog_CircularReferenceDetected {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created parameter {0} ({1}) for type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedParameter {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End creating type {0}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating parameter {0} ({1}) for type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingParameter {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start creating type {0} using {1}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0} value using {1}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingValue {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_IgnoringProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_IgnoringProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped type requested from {0} to {1}.
        /// </summary>
        internal static string DefaultBuildLog_MappingType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_MappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End populating instance {0}.
        /// </summary>
        internal static string DefaultBuildLog_PopulatedInstance {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PopulatedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start populating instance {0}.
        /// </summary>
        internal static string DefaultBuildLog_PopulatingInstance {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PopulatingInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running PostBuild on {0} using {1}.
        /// </summary>
        internal static string DefaultBuildLog_PostBuild {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PostBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000dn.com
        ///013net.net
        ///100im.info
        ///101affiliates.com
        ///10best.com
        ///11oyun.com
        ///120sports.com
        ///123c.vn
        ///123mua.vn
        ///123pay.vn
        ///123phim.vn
        ///123-reg.co.uk
        ///123rf.com
        ///123srv.com
        ///1337x.org
        ///140proof.com
        ///163.com
        ///1688.com
        ///16mm.it
        ///173uu.com
        ///17ok.com
        ///1and1.co.uk
        ///1and1.com
        ///1anh.com
        ///1dial.com
        ///1digitalstock.com
        ///1iota.com
        ///1mobile.com
        ///1up.com
        ///1worldonline.com
        ///20minutos.es
        ///22find.com
        ///2345.com
        ///247inc.net
        ///247-inc.net
        ///247msg.com
        ///247realmedia.com
        ///247sports.com
        ///247wallst.com
        ///24h.com.vn
        ///24h-hotel.com
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Domains {
            get {
                return ResourceManager.GetString("Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; does not refer to a property.
        /// </summary>
        internal static string Error_ExpressionNotPropertyFormat {
            get {
                return ResourceManager.GetString("Error_ExpressionNotPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression returned a property {0} that was not defined on type &apos;{1}&apos;.
        /// </summary>
        internal static string Error_ExpressionTargetsWrongType {
            get {
                return ResourceManager.GetString("Error_ExpressionTargetsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support the {1} type and reference name {2} in the context of the current build chain.
        /// </summary>
        internal static string Error_GenerationNotSupportedFormat {
            get {
                return ResourceManager.GetString("Error_GenerationNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support the {1} type.
        /// </summary>
        internal static string Error_TypeNotSupportedFormat {
            get {
                return ResourceManager.GetString("Error_TypeNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BuildChain property on the execution strategy is null.
        /// </summary>
        internal static string ExecuteStrategy_NoBuildChain {
            get {
                return ResourceManager.GetString("ExecuteStrategy_NoBuildChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaren
        ///Abagael
        ///Abagail
        ///Abbe
        ///Abbey
        ///Abbie
        ///Abby
        ///Abbye
        ///Abigael
        ///Abigale
        ///Abra
        ///Ada
        ///Adah
        ///Adaline
        ///Adan
        ///Adara
        ///Adda
        ///Addi
        ///Addy
        ///Adel
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelheid
        ///Adelice
        ///Adelina
        ///Adelind
        ///Adeline
        ///Adella
        ///Adelle
        ///Adena
        ///Adi
        ///Adiana
        ///Adina
        ///Adore
        ///Adoree
        ///Adrea
        ///Adria
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adriena
        ///Adrienne
        ///Aeriela
        ///Ag
        ///Agace
        ///Agata
        ///Agatha
        ///Aggi
        ///Aggie
        ///Aggy
        ///Agna
        ///Agnella
        ///Agnes
        ///Agnola
        ///Agretha
        ///Aida
        ///Aidan
        ///Aigneis
        ///Aila
        ///Aile
        ///Ailee
        ///Aileen
        ///Ailene
        ///Aili
        ///Ailina
        ///Ailis
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaronsohn
        ///Abade
        ///Abbatucci
        ///Abbets
        ///Abbiss
        ///Abdie
        ///Abdy
        ///Abele
        ///Aberdalgy
        ///Abernethy
        ///Ableson
        ///Ablett
        ///Ablott
        ///Abrahamoff
        ///Abrahamsen
        ///Abrahamsohn
        ///Abrahmson
        ///Abramamov
        ///Abramcik
        ///Abramin
        ///Abramovitz
        ///Abramowitch
        ///Abramzon
        ///Abrey
        ///Acaster
        ///Acock
        ///Adame
        ///Adamiec
        ///Adams
        ///Adamthwaite
        ///Adan
        ///Adanez
        ///Adderson
        ///Ades
        ///Adney
        ///Adolf
        ///Adolfsen
        ///Adolfson
        ///Adrien
        ///Adrienne
        ///Adshed
        ///Advani
        ///Affuso
        ///Ager
        ///Agerskow
        ///Aggio
        ///Agiolfinger
        ///Aguirrezabal
        ///Aguirrezabala
        ///Ahern
        ///Ahrenius
        ///Ahrens
        ///Aiken
        ///Aikin
        ///Ailsbury
        ///Aimer
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia,New South Wales,Sydney,1009,Bunker Hill,Junction,+61 140 836 9230
        ///Australia,New South Wales,Sydney,1109,Miller,Road,+61 939 821 6963
        ///Australia,Australian Capital Territory,Canberra,2600,Sachtjen,Street,+61 613 266 0635
        ///Australia,South Australia,Adelaide,5889,Bultman,Park,+61 752 287 8617
        ///Australia,South Australia,Adelaide,5899,Ohio,Hill,+61 573 292 8781
        ///Australia,Tasmania,Hobart,7803,School,Park,+61 492 805 3353
        ///Australia,Tasmania,Hobart,7808,Green Ridge,Pass,+61 810 522 2352
        ///Australia,West [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Ab
        ///Abba
        ///Abbie
        ///Abbot
        ///Abbott
        ///Abdul
        ///Abe
        ///Abel
        ///Abelard
        ///Abeu
        ///Abey
        ///Abie
        ///Abner
        ///Abraham
        ///Abrahan
        ///Abram
        ///Abramo
        ///Abran
        ///Ad
        ///Adair
        ///Adam
        ///Adamo
        ///Adams
        ///Adan
        ///Addie
        ///Addy
        ///Ade
        ///Adelbert
        ///Adham
        ///Adlai
        ///Adler
        ///Ado
        ///Adolf
        ///Adolph
        ///Adolphe
        ///Adolpho
        ///Adolphus
        ///Adrian
        ///Adriano
        ///Adrien
        ///Agosto
        ///Aguie
        ///Aguistin
        ///Agustin
        ///Ahmad
        ///Ahmed
        ///Ailbert
        ///Akim
        ///Aksel
        ///Al
        ///Alain
        ///Alair
        ///Alan
        ///Aland
        ///Alano
        ///Alanson
        ///Alard
        ///Alaric
        ///Alasdair
        ///Alastair
        ///Alasteir
        ///Alaster
        ///Alberik
        ///Albert
        ///Alberto
        ///Albie
        ///Albrecht
        ///Aldin
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supporting ITypeCreator or IValueGenerator was found to build the type &apos;{0}&apos;.
        /// </summary>
        internal static string NoMatchingCreatorOrGeneratorFound {
            get {
                return ResourceManager.GetString("NoMatchingCreatorOrGeneratorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supporting ITypeCreator or IValueGenerator was found to build the type &apos;{0}&apos; for &apos;{1}&apos;.
        /// </summary>
        internal static string NoMatchingCreatorOrGeneratorFoundWithName {
            get {
                return ResourceManager.GetString("NoMatchingCreatorOrGeneratorFoundWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supporting ITypeCreator or IValueGenerator was found to build the type &apos;{0}&apos; for &apos;{1}&apos; on type &apos;{2}&apos;.
        /// </summary>
        internal static string NoMatchingCreatorOrGeneratorFoundWithNameAndContext {
            get {
                return ResourceManager.GetString("NoMatchingCreatorOrGeneratorFoundWithNameAndContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either declaringType, propertyType or propertyExpression must be supplied.
        /// </summary>
        internal static string NoOwnerTypePropertyTypeOrPropertyExpression {
            get {
                return ResourceManager.GetString("NoOwnerTypePropertyTypeOrPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either declaringType, propertyType or propertyName must be supplied.
        /// </summary>
        internal static string NoOwnerTypePropertyTypeOrPropertyName {
            get {
                return ResourceManager.GetString("NoOwnerTypePropertyTypeOrPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either propertyType or propertyExpression must be supplied.
        /// </summary>
        internal static string NoPropertyTypeOrPropertyExpression {
            get {
                return ResourceManager.GetString("NoPropertyTypeOrPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either propertyType or propertyName must be supplied.
        /// </summary>
        internal static string NoPropertyTypeOrPropertyName {
            get {
                return ResourceManager.GetString("NoPropertyTypeOrPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either targetType or propertyExpression must be supplied.
        /// </summary>
        internal static string NoTargetTypeOrPropertyExpression {
            get {
                return ResourceManager.GetString("NoTargetTypeOrPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either targetType or propertyName must be supplied.
        /// </summary>
        internal static string NoTargetTypeOrPropertyName {
            get {
                return ResourceManager.GetString("NoTargetTypeOrPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This generator was not created with a source expression. Call GetValue&lt;T&gt;(expression, context) instead.
        /// </summary>
        internal static string RelativeValueGenerator_NoSourceExpression {
            get {
                return ResourceManager.GetString("RelativeValueGenerator_NoSourceExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule {0} does not support type &apos;{1}&apos; for &apos;{2}&apos;.
        /// </summary>
        internal static string Rule_InvalidMatch {
            get {
                return ResourceManager.GetString("Rule_InvalidMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Abidjan
        ///Africa/Accra
        ///Africa/Addis_Ababa
        ///Africa/Algiers
        ///Africa/Asmara
        ///Africa/Asmera
        ///Africa/Bamako
        ///Africa/Bangui
        ///Africa/Banjul
        ///Africa/Bissau
        ///Africa/Blantyre
        ///Africa/Brazzaville
        ///Africa/Bujumbura
        ///Africa/Cairo
        ///Africa/Casablanca
        ///Africa/Ceuta
        ///Africa/Conakry
        ///Africa/Dakar
        ///Africa/Dar_es_Salaam
        ///Africa/Djibouti
        ///Africa/Douala
        ///Africa/El_Aaiun
        ///Africa/Freetown
        ///Africa/Gaborone
        ///Africa/Harare
        ///Africa/Johannesburg
        ///Africa/Juba
        ///Africa/Kampala
        ///Africa/Khartoum
        ///Africa/Kigali
        ///Africa/Kinshasa
        ///Afric [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeZones {
            get {
                return ResourceManager.GetString("TimeZones", resourceCulture);
            }
        }
    }
}
