//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBuilder.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelBuilder.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null, white space or empty.
        /// </summary>
        internal static string ArgumentException_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentException_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not return an {1} instance. A build log is required to create an {2} instance.
        /// </summary>
        internal static string BuildStrategy_BuildLogRequired {
            get {
                return ResourceManager.GetString("BuildStrategy_BuildLogRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ConstructorResolver is null. A constructor resolver must be provided in order to create a build strategy.
        /// </summary>
        internal static string BuildStrategyCompiler_NullConstructorResolver {
            get {
                return ResourceManager.GetString("BuildStrategyCompiler_NullConstructorResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PropertyResolver is null. A property resolver must be provided in order to create a build strategy.
        /// </summary>
        internal static string BuildStrategyCompiler_NullPropertyResolver {
            get {
                return ResourceManager.GetString("BuildStrategyCompiler_NullPropertyResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public constructor is available for type {0}.
        /// </summary>
        internal static string ConstructorResolver_NoPublicConstructorFound {
            get {
                return ResourceManager.GetString("ConstructorResolver_NoPublicConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid constructors are available for type {0}.
        /// </summary>
        internal static string ConstructorResolver_NoValidConstructorFound {
            get {
                return ResourceManager.GetString("ConstructorResolver_NoValidConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aa-DJ
        ///aa-ER
        ///aa-ET
        ///af
        ///af-NA
        ///af-ZA
        ///agq
        ///agq-CM
        ///ak
        ///ak-GH
        ///am
        ///am-ET
        ///ar
        ///ar-001
        ///ar-AE
        ///ar-BH
        ///ar-DJ
        ///ar-DZ
        ///ar-EG
        ///ar-ER
        ///ar-IL
        ///ar-IQ
        ///ar-JO
        ///ar-KM
        ///ar-KW
        ///ar-LB
        ///ar-LY
        ///ar-MA
        ///ar-MR
        ///ar-OM
        ///ar-PS
        ///ar-QA
        ///ar-SA
        ///ar-SD
        ///ar-SO
        ///ar-SS
        ///ar-SY
        ///ar-TD
        ///ar-TN
        ///ar-YE
        ///arn
        ///arn-CL
        ///as
        ///as-IN
        ///asa
        ///asa-TZ
        ///ast
        ///ast-ES
        ///az
        ///az-Cyrl
        ///az-Cyrl-AZ
        ///az-Latn
        ///az-Latn-AZ
        ///ba
        ///ba-RU
        ///bas
        ///bas-CM
        ///be
        ///be-BY
        ///bem
        ///bem-ZM
        ///bez
        ///bez-TZ
        ///bg
        ///bg-BG
        ///bin
        ///bin-NG
        ///bm
        ///bm-Latn
        ///bm-Latn-ML
        ///bn
        ///bn-BD
        ///bn-IN
        ///bo
        ///bo-CN
        ///bo-IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected circular reference building type {0}, using previously created instance.
        /// </summary>
        internal static string DefaultBuildLog_CircularReferenceDetected {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created parameter {0} ({1}) for type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedParameter {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End creating type {0}.
        /// </summary>
        internal static string DefaultBuildLog_CreatedType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating parameter {0} ({1}) for type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingParameter {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start creating type {0} using {1}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingType {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0} value using {1}.
        /// </summary>
        internal static string DefaultBuildLog_CreatingValue {
            get {
                return ResourceManager.GetString("DefaultBuildLog_CreatingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring property {0} ({1}) on type {2}.
        /// </summary>
        internal static string DefaultBuildLog_IgnoringProperty {
            get {
                return ResourceManager.GetString("DefaultBuildLog_IgnoringProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End populating instance {0}.
        /// </summary>
        internal static string DefaultBuildLog_PopulatedInstance {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PopulatedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start populating instance {0}.
        /// </summary>
        internal static string DefaultBuildLog_PopulatingInstance {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PopulatingInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running PostBuild on {0} using {1}.
        /// </summary>
        internal static string DefaultBuildLog_PostBuild {
            get {
                return ResourceManager.GetString("DefaultBuildLog_PostBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; does not refer to a property.
        /// </summary>
        internal static string Error_ExpressionNotPropertyFormat {
            get {
                return ResourceManager.GetString("Error_ExpressionNotPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression returned a property {0} that was not defined on type &apos;{1}&apos;.
        /// </summary>
        internal static string Error_ExpressionTargetsWrongType {
            get {
                return ResourceManager.GetString("Error_ExpressionTargetsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support the {1} type and reference name {2} in the context of the current build chain.
        /// </summary>
        internal static string Error_GenerationNotSupportedFormat {
            get {
                return ResourceManager.GetString("Error_GenerationNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support the {1} type.
        /// </summary>
        internal static string Error_TypeNotSupportedFormat {
            get {
                return ResourceManager.GetString("Error_TypeNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BuildChain property on the execution strategy is null.
        /// </summary>
        internal static string ExecuteStrategy_NoBuildChain {
            get {
                return ResourceManager.GetString("ExecuteStrategy_NoBuildChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaren
        ///Abagael
        ///Abagail
        ///Abbe
        ///Abbey
        ///Abbie
        ///Abby
        ///Abbye
        ///Abigael
        ///Abigale
        ///Abra
        ///Ada
        ///Adah
        ///Adaline
        ///Adan
        ///Adara
        ///Adda
        ///Addi
        ///Addy
        ///Adel
        ///Adelaida
        ///Adelaide
        ///Adele
        ///Adelheid
        ///Adelice
        ///Adelina
        ///Adelind
        ///Adeline
        ///Adella
        ///Adelle
        ///Adena
        ///Adi
        ///Adiana
        ///Adina
        ///Adore
        ///Adoree
        ///Adrea
        ///Adria
        ///Adriana
        ///Adriane
        ///Adrianna
        ///Adrianne
        ///Adriena
        ///Adrienne
        ///Aeriela
        ///Ag
        ///Agace
        ///Agata
        ///Agatha
        ///Aggi
        ///Aggie
        ///Aggy
        ///Agna
        ///Agnella
        ///Agnes
        ///Agnola
        ///Agretha
        ///Aida
        ///Aidan
        ///Aigneis
        ///Aila
        ///Aile
        ///Ailee
        ///Aileen
        ///Ailene
        ///Aili
        ///Ailina
        ///Ailis
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaronsohn
        ///Abade
        ///Abbatucci
        ///Abbets
        ///Abbiss
        ///Abdie
        ///Abdy
        ///Abele
        ///Aberdalgy
        ///Abernethy
        ///Ableson
        ///Ablett
        ///Ablott
        ///Abrahamoff
        ///Abrahamsen
        ///Abrahamsohn
        ///Abrahmson
        ///Abramamov
        ///Abramcik
        ///Abramin
        ///Abramovitz
        ///Abramowitch
        ///Abramzon
        ///Abrey
        ///Acaster
        ///Acock
        ///Adame
        ///Adamiec
        ///Adams
        ///Adamthwaite
        ///Adan
        ///Adanez
        ///Adderson
        ///Ades
        ///Adney
        ///Adolf
        ///Adolfsen
        ///Adolfson
        ///Adrien
        ///Adrienne
        ///Adshed
        ///Advani
        ///Affuso
        ///Ager
        ///Agerskow
        ///Aggio
        ///Agiolfinger
        ///Aguirrezabal
        ///Aguirrezabala
        ///Ahern
        ///Ahrenius
        ///Ahrens
        ///Aiken
        ///Aikin
        ///Ailsbury
        ///Aimer
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country,State,City,PostCode,StreetName,StreetSuffix
        ///Australia,New South Wales,Eastern Suburbs Mc,1315,Dawn,Terrace
        ///Australia,New South Wales,Eastern Suburbs Mc,1315,Hansons,Alley
        ///Australia,New South Wales,Sydney,1043,Donald,Park
        ///Australia,New South Wales,Sydney,1109,Melvin,Street
        ///Australia,New South Wales,Sydney,1130,Warner,Drive
        ///Australia,New South Wales,Sydney,1196,Golf Course,Parkway
        ///Australia,South Australia,Adelaide Mail Centre,5869,Eagle Crest,Lane
        ///Australia,South Australia,Adelaide Mail Centr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Ab
        ///Abba
        ///Abbie
        ///Abbot
        ///Abbott
        ///Abdul
        ///Abe
        ///Abel
        ///Abelard
        ///Abeu
        ///Abey
        ///Abie
        ///Abner
        ///Abraham
        ///Abrahan
        ///Abram
        ///Abramo
        ///Abran
        ///Ad
        ///Adair
        ///Adam
        ///Adamo
        ///Adams
        ///Adan
        ///Addie
        ///Addy
        ///Ade
        ///Adelbert
        ///Adham
        ///Adlai
        ///Adler
        ///Ado
        ///Adolf
        ///Adolph
        ///Adolphe
        ///Adolpho
        ///Adolphus
        ///Adrian
        ///Adriano
        ///Adrien
        ///Agosto
        ///Aguie
        ///Aguistin
        ///Agustin
        ///Ahmad
        ///Ahmed
        ///Ailbert
        ///Akim
        ///Aksel
        ///Al
        ///Alain
        ///Alair
        ///Alan
        ///Aland
        ///Alano
        ///Alanson
        ///Alard
        ///Alaric
        ///Alasdair
        ///Alastair
        ///Alasteir
        ///Alaster
        ///Alberik
        ///Albert
        ///Alberto
        ///Albie
        ///Albrecht
        ///Aldin
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supporting ITypeCreator or IValueGenerator was found to build the type &apos;{0}&apos;.
        /// </summary>
        internal static string NoMatchingCreatorOrGeneratorFound {
            get {
                return ResourceManager.GetString("NoMatchingCreatorOrGeneratorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supporting ITypeCreator or IValueGenerator was found to build the type &apos;{0}&apos; for &apos;{1}&apos;.
        /// </summary>
        internal static string NoMatchingCreatorOrGeneratorFoundWithName {
            get {
                return ResourceManager.GetString("NoMatchingCreatorOrGeneratorFoundWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supporting ITypeCreator or IValueGenerator was found to build the type &apos;{0}&apos; for &apos;{1}&apos; on type &apos;{2}&apos;.
        /// </summary>
        internal static string NoMatchingCreatorOrGeneratorFoundWithNameAndContext {
            get {
                return ResourceManager.GetString("NoMatchingCreatorOrGeneratorFoundWithNameAndContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either declaringType, propertyType or propertyExpression must be supplied.
        /// </summary>
        internal static string NoOwnerTypePropertyTypeOrPropertyExpression {
            get {
                return ResourceManager.GetString("NoOwnerTypePropertyTypeOrPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either declaringType, propertyType or propertyName must be supplied.
        /// </summary>
        internal static string NoOwnerTypePropertyTypeOrPropertyName {
            get {
                return ResourceManager.GetString("NoOwnerTypePropertyTypeOrPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either propertyType or propertyExpression must be supplied.
        /// </summary>
        internal static string NoPropertyTypeOrPropertyExpression {
            get {
                return ResourceManager.GetString("NoPropertyTypeOrPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either propertyType or propertyName must be supplied.
        /// </summary>
        internal static string NoPropertyTypeOrPropertyName {
            get {
                return ResourceManager.GetString("NoPropertyTypeOrPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either targetType or propertyExpression must be supplied.
        /// </summary>
        internal static string NoTargetTypeOrPropertyExpression {
            get {
                return ResourceManager.GetString("NoTargetTypeOrPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either targetType or propertyName must be supplied.
        /// </summary>
        internal static string NoTargetTypeOrPropertyName {
            get {
                return ResourceManager.GetString("NoTargetTypeOrPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;People xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Person&gt;&lt;Address&gt;997 Emmet Circle&lt;/Address&gt;&lt;City&gt;Newark&lt;/City&gt;&lt;Company&gt;Tanoodle&lt;/Company&gt;&lt;Country&gt;Benin&lt;/Country&gt;&lt;Domain&gt;google.ca&lt;/Domain&gt;&lt;Email&gt;tspencer0@is.gd&lt;/Email&gt;&lt;FirstName&gt;Theresa&lt;/FirstName&gt;&lt;Gender&gt;Female&lt;/Gender&gt;&lt;LastName&gt;Spencer&lt;/LastName&gt;&lt;Phone&gt;1-(302)560-3674&lt;/Phone&gt;&lt;PostCode&gt;19714&lt;/PostCode&gt;&lt;State&gt;Delaware&lt;/State&gt;&lt;TimeZone&gt;America/Mexico_City&lt;/TimeZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This generator was not created with a source expression. Call GetValue&lt;T&gt;(expression, context) instead.
        /// </summary>
        internal static string RelativeValueGenerator_NoSourceExpression {
            get {
                return ResourceManager.GetString("RelativeValueGenerator_NoSourceExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule {0} does not support type &apos;{1}&apos; for &apos;{2}&apos;.
        /// </summary>
        internal static string Rule_InvalidMatch {
            get {
                return ResourceManager.GetString("Rule_InvalidMatch", resourceCulture);
            }
        }
    }
}
