name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch tags and master for GitVersion
      run: |
        git fetch --tags
        git branch --create-reflog master origin/master

    - name: GitVersion
      uses: docker://gittools/gitversion:5.0.2-linux
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_NuGetVersionV2 > /github/workspace/version.txt\""
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103' # SDK Version to use.
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -f netstandard1.5
    - name: Test
      run: dotnet test --no-build -f netstandard1.5
